//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Script/Input System/Player Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Controls"",
    ""maps"": [
        {
            ""name"": ""Loading UI"",
            ""id"": ""5593f047-3883-44fc-a57f-1b305e4e4c9e"",
            ""actions"": [
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""e802b13c-6ba3-4eb1-aa4e-0f964953108d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b75126c2-acc7-49f3-a5a9-da25e6329052"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4b6a37e-5e19-4be1-9b56-dbb1e28d417f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player"",
            ""id"": ""51c15480-5370-447b-adb0-c9ad5ac3cb07"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""36e1b5f6-e05f-44dc-977c-d1f1ef32e871"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a7507668-ddc6-49b3-a582-544465b17fc0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""1454e48b-ff70-4afb-8e1f-450107e355cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""acf2fb44-6f12-4a87-8c95-d5b6955dff70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""7fe1ce58-ad42-41a7-8625-af95789a3dd1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""87071bd6-cc80-408f-8b6f-b879ec2d3146"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""f83ab4bf-236a-4982-b3cf-964c124ad68e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Examine"",
                    ""type"": ""Button"",
                    ""id"": ""1c17f783-06a1-4f5f-a14f-c427c30fcb0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""a642dcd7-bf03-4cdd-9896-026d89ca99a0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""46962e0b-8eeb-4595-b1d7-f2a1837c0b09"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3a524619-135e-4965-bba6-05076d230445"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""12528707-34b9-4c63-a6a0-7a5e068a4152"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""219e7a0e-741d-43f5-a6da-039a27f7faf0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""019eff02-2935-4c59-b027-51a6f9f58990"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f843dc89-bd7e-416b-9618-eb3d43882359"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aff8db38-1dab-462c-b39f-f73f3301e6ed"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fca2e006-2f1b-4dd0-8546-703fc2acf8e3"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99448c01-6848-4a4a-a800-9529dd18b3fe"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bf35011-2197-4aed-a160-36a5a1f987bc"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""249bfb3f-a898-489d-8810-25171b5ab578"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""136b35e4-08b0-4c90-822d-c869673fd296"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3770c3a9-782f-4468-a3b7-c998349915d8"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cda46a94-af5e-4bc5-9562-455978fab6ee"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ff1fec8-4e0d-48cc-a89d-5f4e06d640a2"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4e184b3-3e4d-4da4-8d66-fca7e99b22c3"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5008bb9d-d55d-4422-86e8-cf8f945014d1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0231d4a9-6008-4127-88c1-c7eaf0b98ad9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Examine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70ef722c-2836-414e-adcf-ce249efdd7a4"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Examine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerLayingDown"",
            ""id"": ""2c545e5a-8a2a-4985-af5e-aff57401b011"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""78b5b408-d749-4183-9793-f42510d7e21b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""7f313553-77d3-4a05-bccb-a01d6f185900"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d8ee114f-db31-4fdb-91cb-4000542df260"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a261a6d-62f3-4198-b799-f9871193764e"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f47eb971-2df5-491c-839c-6abe0d5e9ff0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6603f9c-adf0-42d4-ba85-b879eb517419"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Examine"",
            ""id"": ""b56fbaaf-9e4b-4acc-9e7e-225d2b9f7b69"",
            ""actions"": [
                {
                    ""name"": ""Lock"",
                    ""type"": ""Button"",
                    ""id"": ""c906acd6-3cd4-424b-a77b-e90ae8886927"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""95b6795f-b3ed-4fa6-939c-2bc4a203fe28"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gamepad Rotation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dcdb7bf6-9dee-4793-a068-ae37483059af"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Read"",
                    ""type"": ""Button"",
                    ""id"": ""689e73a9-e957-4a30-9ca7-29e4efff7607"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""faa6b704-a643-4e35-93c9-4548a7a901b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""33421041-c900-45d1-af5e-8c53fd3c4d79"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e44d668-d708-469a-8509-0b011c1a7918"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""318fafb9-c513-42de-a66a-31f18be736ec"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d60e27f8-4067-45c4-933e-05bab0e56b72"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gamepad Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86ccaf20-a5ed-42e9-92fa-6e7d6f57adee"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Read"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6760022-9f97-4dff-8c2b-6948dad324cc"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Read"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""982b3208-1f17-470b-a689-42fac24efdf1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9b80b81-c2e3-4341-8ae5-6ecbea42e8ef"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Speech Dialogue"",
            ""id"": ""b01883fb-61ca-4310-9e4a-01b18353cf7c"",
            ""actions"": [
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""ffbb66fd-75ca-489e-b676-2ae6432e664e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Option 1"",
                    ""type"": ""Button"",
                    ""id"": ""278ee2e1-4deb-4b61-9118-9f4ed220d85a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Option 2"",
                    ""type"": ""Button"",
                    ""id"": ""5bd79307-d2b6-4031-91e7-8b08ccf12c13"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Option 3"",
                    ""type"": ""Button"",
                    ""id"": ""f10b7aaf-a99e-49af-b50e-dfe911270c9b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7f7b5253-d092-491d-9134-868f4987ae5c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea177573-a32f-494a-9f8b-dfe9471a57be"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4f44a63-e4e7-4eeb-96a7-2f8afa9f0868"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Option 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5f1aa92-b032-4d03-808f-0822c5d133e1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Option 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9de26f8-a7f4-4f75-975f-13c507c7b9e0"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Option 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""319f499a-3f27-4d4f-bb66-ea0c7a4870af"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Option 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4628f07-5f09-49d0-be9b-f04c5ce8b389"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Option 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f46e7948-bdab-4cc6-8c6a-23503295ff98"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Option 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Contact"",
            ""id"": ""e17599e3-f4d2-44c6-89a2-c1051c9081a4"",
            ""actions"": [
                {
                    ""name"": ""Contact1"",
                    ""type"": ""Button"",
                    ""id"": ""f922a647-e42a-429d-965f-390d2b669c25"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Contact2"",
                    ""type"": ""Button"",
                    ""id"": ""a17564ae-bd42-46d9-a22b-295898818ee5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Contact3"",
                    ""type"": ""Button"",
                    ""id"": ""16e7d19f-ee3c-4c74-83e2-376121e1fbe0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e7a7bbfe-55d4-4bb4-a1fc-bf7fb85c3f53"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Contact1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""687331cc-22c8-4f42-858b-c1e9b3594fde"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Contact1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5998edd4-6286-447f-98a7-5ae84d916458"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Contact2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67b8c092-4915-4417-9252-def9c3ea542f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Contact2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10b76387-0eaa-4b23-96d8-6780e8a67a4d"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Contact3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8efc36bf-be5b-4282-b447-63d238070b3a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Contact3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Extinguisher"",
            ""id"": ""2230b633-33ef-4baa-81b5-4419c0e4e34a"",
            ""actions"": [
                {
                    ""name"": ""Twist"",
                    ""type"": ""Button"",
                    ""id"": ""9f32ba36-86e0-464b-815e-aa4671696ca9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pull"",
                    ""type"": ""Button"",
                    ""id"": ""a629a1c5-509a-402c-a8fa-10d1039a55b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""b083d617-37ad-46fb-9a72-94d57e2a214b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Squeeze"",
                    ""type"": ""Button"",
                    ""id"": ""6f17fd27-678f-4f00-9d11-5ddcba76d63d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sweep"",
                    ""type"": ""Button"",
                    ""id"": ""9f7c8143-55ad-43e1-ae11-857495cc6b42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""94cb8fae-fa96-4d28-93bc-283a51486743"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Twist"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce6ccbde-e941-4d37-b05a-205aefdd416d"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Twist"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd0dfd2c-301a-4d7e-aa8e-411b823b377c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4406bd70-3065-4556-9eae-b4f193cd1d9b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4060e14-d9db-443f-b98d-b18dc1906140"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf8e6d48-c421-4db2-91cb-5670ecd36bb8"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f50fd96a-5d57-4db5-a567-597d66ecf351"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Squeeze"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e65cc18b-b2e8-445f-b2c9-ef3a787b70b6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sweep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a693136d-2196-4a93-a262-91d056290dae"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sweep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TwistFE"",
            ""id"": ""178c81df-3667-4958-9eda-ca4f09c81fea"",
            ""actions"": [
                {
                    ""name"": ""Button 1"",
                    ""type"": ""Button"",
                    ""id"": ""b39f2e73-efa0-4c3b-8620-ae48e0671590"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button 2"",
                    ""type"": ""Button"",
                    ""id"": ""dce60e61-afc7-4267-ab35-695d6928890a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button 3"",
                    ""type"": ""Button"",
                    ""id"": ""4dd55d80-e77e-43e9-b65e-7f5aa85a8a04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button 4"",
                    ""type"": ""Button"",
                    ""id"": ""4d38640f-8fe6-44d8-b78a-a2bd045dd4a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""304336a5-6102-4eb9-b53f-c39a72e815db"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82a619a1-db1a-435d-a93c-25f8d4faeb3a"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66bd61e8-0f33-4931-b2cc-39363b7b3fe6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""210db986-504b-440e-aeed-0494c3503c54"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebbf5c3b-182f-4c00-b0ae-c3bdabf40ddc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41b67be7-f773-465f-94bb-0ce05a92ef0b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f4baa1a-6a55-4554-9571-f261ac5e47ae"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57721457-bbf7-4e50-abf1-64d6febec4c4"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PullFE"",
            ""id"": ""85be5eb6-0ae8-4a2a-bcd6-f5886c706f53"",
            ""actions"": [
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""99f7896b-b28e-4c5d-8baa-6c026a34d2e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action Lock"",
                    ""type"": ""Button"",
                    ""id"": ""c83f9c82-b5c5-47a5-bf1e-d3a385ffc7ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b20e7ed6-4fb2-41d8-8261-4413a8a4588b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b144feeb-0509-4ed3-8e67-dc9cec3d8829"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5279220b-0310-40d4-a698-c768d7ba8dac"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action Lock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71dc329d-ed78-4681-bb13-556685a42852"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action Lock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Loading UI
        m_LoadingUI = asset.FindActionMap("Loading UI", throwIfNotFound: true);
        m_LoadingUI_Action = m_LoadingUI.FindAction("Action", throwIfNotFound: true);
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        m_Player_Crouch = m_Player.FindAction("Crouch", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_Examine = m_Player.FindAction("Examine", throwIfNotFound: true);
        // PlayerLayingDown
        m_PlayerLayingDown = asset.FindActionMap("PlayerLayingDown", throwIfNotFound: true);
        m_PlayerLayingDown_Look = m_PlayerLayingDown.FindAction("Look", throwIfNotFound: true);
        m_PlayerLayingDown_Action = m_PlayerLayingDown.FindAction("Action", throwIfNotFound: true);
        // Examine
        m_Examine = asset.FindActionMap("Examine", throwIfNotFound: true);
        m_Examine_Lock = m_Examine.FindAction("Lock", throwIfNotFound: true);
        m_Examine_Rotation = m_Examine.FindAction("Rotation", throwIfNotFound: true);
        m_Examine_GamepadRotation = m_Examine.FindAction("Gamepad Rotation", throwIfNotFound: true);
        m_Examine_Read = m_Examine.FindAction("Read", throwIfNotFound: true);
        m_Examine_Back = m_Examine.FindAction("Back", throwIfNotFound: true);
        // Speech Dialogue
        m_SpeechDialogue = asset.FindActionMap("Speech Dialogue", throwIfNotFound: true);
        m_SpeechDialogue_Action = m_SpeechDialogue.FindAction("Action", throwIfNotFound: true);
        m_SpeechDialogue_Option1 = m_SpeechDialogue.FindAction("Option 1", throwIfNotFound: true);
        m_SpeechDialogue_Option2 = m_SpeechDialogue.FindAction("Option 2", throwIfNotFound: true);
        m_SpeechDialogue_Option3 = m_SpeechDialogue.FindAction("Option 3", throwIfNotFound: true);
        // Contact
        m_Contact = asset.FindActionMap("Contact", throwIfNotFound: true);
        m_Contact_Contact1 = m_Contact.FindAction("Contact1", throwIfNotFound: true);
        m_Contact_Contact2 = m_Contact.FindAction("Contact2", throwIfNotFound: true);
        m_Contact_Contact3 = m_Contact.FindAction("Contact3", throwIfNotFound: true);
        // Extinguisher
        m_Extinguisher = asset.FindActionMap("Extinguisher", throwIfNotFound: true);
        m_Extinguisher_Twist = m_Extinguisher.FindAction("Twist", throwIfNotFound: true);
        m_Extinguisher_Pull = m_Extinguisher.FindAction("Pull", throwIfNotFound: true);
        m_Extinguisher_Aim = m_Extinguisher.FindAction("Aim", throwIfNotFound: true);
        m_Extinguisher_Squeeze = m_Extinguisher.FindAction("Squeeze", throwIfNotFound: true);
        m_Extinguisher_Sweep = m_Extinguisher.FindAction("Sweep", throwIfNotFound: true);
        // TwistFE
        m_TwistFE = asset.FindActionMap("TwistFE", throwIfNotFound: true);
        m_TwistFE_Button1 = m_TwistFE.FindAction("Button 1", throwIfNotFound: true);
        m_TwistFE_Button2 = m_TwistFE.FindAction("Button 2", throwIfNotFound: true);
        m_TwistFE_Button3 = m_TwistFE.FindAction("Button 3", throwIfNotFound: true);
        m_TwistFE_Button4 = m_TwistFE.FindAction("Button 4", throwIfNotFound: true);
        // PullFE
        m_PullFE = asset.FindActionMap("PullFE", throwIfNotFound: true);
        m_PullFE_Action = m_PullFE.FindAction("Action", throwIfNotFound: true);
        m_PullFE_ActionLock = m_PullFE.FindAction("Action Lock", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Loading UI
    private readonly InputActionMap m_LoadingUI;
    private List<ILoadingUIActions> m_LoadingUIActionsCallbackInterfaces = new List<ILoadingUIActions>();
    private readonly InputAction m_LoadingUI_Action;
    public struct LoadingUIActions
    {
        private @PlayerControls m_Wrapper;
        public LoadingUIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Action => m_Wrapper.m_LoadingUI_Action;
        public InputActionMap Get() { return m_Wrapper.m_LoadingUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LoadingUIActions set) { return set.Get(); }
        public void AddCallbacks(ILoadingUIActions instance)
        {
            if (instance == null || m_Wrapper.m_LoadingUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LoadingUIActionsCallbackInterfaces.Add(instance);
            @Action.started += instance.OnAction;
            @Action.performed += instance.OnAction;
            @Action.canceled += instance.OnAction;
        }

        private void UnregisterCallbacks(ILoadingUIActions instance)
        {
            @Action.started -= instance.OnAction;
            @Action.performed -= instance.OnAction;
            @Action.canceled -= instance.OnAction;
        }

        public void RemoveCallbacks(ILoadingUIActions instance)
        {
            if (m_Wrapper.m_LoadingUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILoadingUIActions instance)
        {
            foreach (var item in m_Wrapper.m_LoadingUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LoadingUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LoadingUIActions @LoadingUI => new LoadingUIActions(this);

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Sprint;
    private readonly InputAction m_Player_Crouch;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_Examine;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputAction @Crouch => m_Wrapper.m_Player_Crouch;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @Examine => m_Wrapper.m_Player_Examine;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Examine.started += instance.OnExamine;
            @Examine.performed += instance.OnExamine;
            @Examine.canceled += instance.OnExamine;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Examine.started -= instance.OnExamine;
            @Examine.performed -= instance.OnExamine;
            @Examine.canceled -= instance.OnExamine;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // PlayerLayingDown
    private readonly InputActionMap m_PlayerLayingDown;
    private List<IPlayerLayingDownActions> m_PlayerLayingDownActionsCallbackInterfaces = new List<IPlayerLayingDownActions>();
    private readonly InputAction m_PlayerLayingDown_Look;
    private readonly InputAction m_PlayerLayingDown_Action;
    public struct PlayerLayingDownActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerLayingDownActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_PlayerLayingDown_Look;
        public InputAction @Action => m_Wrapper.m_PlayerLayingDown_Action;
        public InputActionMap Get() { return m_Wrapper.m_PlayerLayingDown; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerLayingDownActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerLayingDownActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerLayingDownActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerLayingDownActionsCallbackInterfaces.Add(instance);
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Action.started += instance.OnAction;
            @Action.performed += instance.OnAction;
            @Action.canceled += instance.OnAction;
        }

        private void UnregisterCallbacks(IPlayerLayingDownActions instance)
        {
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Action.started -= instance.OnAction;
            @Action.performed -= instance.OnAction;
            @Action.canceled -= instance.OnAction;
        }

        public void RemoveCallbacks(IPlayerLayingDownActions instance)
        {
            if (m_Wrapper.m_PlayerLayingDownActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerLayingDownActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerLayingDownActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerLayingDownActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerLayingDownActions @PlayerLayingDown => new PlayerLayingDownActions(this);

    // Examine
    private readonly InputActionMap m_Examine;
    private List<IExamineActions> m_ExamineActionsCallbackInterfaces = new List<IExamineActions>();
    private readonly InputAction m_Examine_Lock;
    private readonly InputAction m_Examine_Rotation;
    private readonly InputAction m_Examine_GamepadRotation;
    private readonly InputAction m_Examine_Read;
    private readonly InputAction m_Examine_Back;
    public struct ExamineActions
    {
        private @PlayerControls m_Wrapper;
        public ExamineActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Lock => m_Wrapper.m_Examine_Lock;
        public InputAction @Rotation => m_Wrapper.m_Examine_Rotation;
        public InputAction @GamepadRotation => m_Wrapper.m_Examine_GamepadRotation;
        public InputAction @Read => m_Wrapper.m_Examine_Read;
        public InputAction @Back => m_Wrapper.m_Examine_Back;
        public InputActionMap Get() { return m_Wrapper.m_Examine; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ExamineActions set) { return set.Get(); }
        public void AddCallbacks(IExamineActions instance)
        {
            if (instance == null || m_Wrapper.m_ExamineActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ExamineActionsCallbackInterfaces.Add(instance);
            @Lock.started += instance.OnLock;
            @Lock.performed += instance.OnLock;
            @Lock.canceled += instance.OnLock;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @GamepadRotation.started += instance.OnGamepadRotation;
            @GamepadRotation.performed += instance.OnGamepadRotation;
            @GamepadRotation.canceled += instance.OnGamepadRotation;
            @Read.started += instance.OnRead;
            @Read.performed += instance.OnRead;
            @Read.canceled += instance.OnRead;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
        }

        private void UnregisterCallbacks(IExamineActions instance)
        {
            @Lock.started -= instance.OnLock;
            @Lock.performed -= instance.OnLock;
            @Lock.canceled -= instance.OnLock;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @GamepadRotation.started -= instance.OnGamepadRotation;
            @GamepadRotation.performed -= instance.OnGamepadRotation;
            @GamepadRotation.canceled -= instance.OnGamepadRotation;
            @Read.started -= instance.OnRead;
            @Read.performed -= instance.OnRead;
            @Read.canceled -= instance.OnRead;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
        }

        public void RemoveCallbacks(IExamineActions instance)
        {
            if (m_Wrapper.m_ExamineActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IExamineActions instance)
        {
            foreach (var item in m_Wrapper.m_ExamineActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ExamineActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ExamineActions @Examine => new ExamineActions(this);

    // Speech Dialogue
    private readonly InputActionMap m_SpeechDialogue;
    private List<ISpeechDialogueActions> m_SpeechDialogueActionsCallbackInterfaces = new List<ISpeechDialogueActions>();
    private readonly InputAction m_SpeechDialogue_Action;
    private readonly InputAction m_SpeechDialogue_Option1;
    private readonly InputAction m_SpeechDialogue_Option2;
    private readonly InputAction m_SpeechDialogue_Option3;
    public struct SpeechDialogueActions
    {
        private @PlayerControls m_Wrapper;
        public SpeechDialogueActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Action => m_Wrapper.m_SpeechDialogue_Action;
        public InputAction @Option1 => m_Wrapper.m_SpeechDialogue_Option1;
        public InputAction @Option2 => m_Wrapper.m_SpeechDialogue_Option2;
        public InputAction @Option3 => m_Wrapper.m_SpeechDialogue_Option3;
        public InputActionMap Get() { return m_Wrapper.m_SpeechDialogue; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SpeechDialogueActions set) { return set.Get(); }
        public void AddCallbacks(ISpeechDialogueActions instance)
        {
            if (instance == null || m_Wrapper.m_SpeechDialogueActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SpeechDialogueActionsCallbackInterfaces.Add(instance);
            @Action.started += instance.OnAction;
            @Action.performed += instance.OnAction;
            @Action.canceled += instance.OnAction;
            @Option1.started += instance.OnOption1;
            @Option1.performed += instance.OnOption1;
            @Option1.canceled += instance.OnOption1;
            @Option2.started += instance.OnOption2;
            @Option2.performed += instance.OnOption2;
            @Option2.canceled += instance.OnOption2;
            @Option3.started += instance.OnOption3;
            @Option3.performed += instance.OnOption3;
            @Option3.canceled += instance.OnOption3;
        }

        private void UnregisterCallbacks(ISpeechDialogueActions instance)
        {
            @Action.started -= instance.OnAction;
            @Action.performed -= instance.OnAction;
            @Action.canceled -= instance.OnAction;
            @Option1.started -= instance.OnOption1;
            @Option1.performed -= instance.OnOption1;
            @Option1.canceled -= instance.OnOption1;
            @Option2.started -= instance.OnOption2;
            @Option2.performed -= instance.OnOption2;
            @Option2.canceled -= instance.OnOption2;
            @Option3.started -= instance.OnOption3;
            @Option3.performed -= instance.OnOption3;
            @Option3.canceled -= instance.OnOption3;
        }

        public void RemoveCallbacks(ISpeechDialogueActions instance)
        {
            if (m_Wrapper.m_SpeechDialogueActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISpeechDialogueActions instance)
        {
            foreach (var item in m_Wrapper.m_SpeechDialogueActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SpeechDialogueActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SpeechDialogueActions @SpeechDialogue => new SpeechDialogueActions(this);

    // Contact
    private readonly InputActionMap m_Contact;
    private List<IContactActions> m_ContactActionsCallbackInterfaces = new List<IContactActions>();
    private readonly InputAction m_Contact_Contact1;
    private readonly InputAction m_Contact_Contact2;
    private readonly InputAction m_Contact_Contact3;
    public struct ContactActions
    {
        private @PlayerControls m_Wrapper;
        public ContactActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Contact1 => m_Wrapper.m_Contact_Contact1;
        public InputAction @Contact2 => m_Wrapper.m_Contact_Contact2;
        public InputAction @Contact3 => m_Wrapper.m_Contact_Contact3;
        public InputActionMap Get() { return m_Wrapper.m_Contact; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ContactActions set) { return set.Get(); }
        public void AddCallbacks(IContactActions instance)
        {
            if (instance == null || m_Wrapper.m_ContactActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ContactActionsCallbackInterfaces.Add(instance);
            @Contact1.started += instance.OnContact1;
            @Contact1.performed += instance.OnContact1;
            @Contact1.canceled += instance.OnContact1;
            @Contact2.started += instance.OnContact2;
            @Contact2.performed += instance.OnContact2;
            @Contact2.canceled += instance.OnContact2;
            @Contact3.started += instance.OnContact3;
            @Contact3.performed += instance.OnContact3;
            @Contact3.canceled += instance.OnContact3;
        }

        private void UnregisterCallbacks(IContactActions instance)
        {
            @Contact1.started -= instance.OnContact1;
            @Contact1.performed -= instance.OnContact1;
            @Contact1.canceled -= instance.OnContact1;
            @Contact2.started -= instance.OnContact2;
            @Contact2.performed -= instance.OnContact2;
            @Contact2.canceled -= instance.OnContact2;
            @Contact3.started -= instance.OnContact3;
            @Contact3.performed -= instance.OnContact3;
            @Contact3.canceled -= instance.OnContact3;
        }

        public void RemoveCallbacks(IContactActions instance)
        {
            if (m_Wrapper.m_ContactActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IContactActions instance)
        {
            foreach (var item in m_Wrapper.m_ContactActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ContactActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ContactActions @Contact => new ContactActions(this);

    // Extinguisher
    private readonly InputActionMap m_Extinguisher;
    private List<IExtinguisherActions> m_ExtinguisherActionsCallbackInterfaces = new List<IExtinguisherActions>();
    private readonly InputAction m_Extinguisher_Twist;
    private readonly InputAction m_Extinguisher_Pull;
    private readonly InputAction m_Extinguisher_Aim;
    private readonly InputAction m_Extinguisher_Squeeze;
    private readonly InputAction m_Extinguisher_Sweep;
    public struct ExtinguisherActions
    {
        private @PlayerControls m_Wrapper;
        public ExtinguisherActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Twist => m_Wrapper.m_Extinguisher_Twist;
        public InputAction @Pull => m_Wrapper.m_Extinguisher_Pull;
        public InputAction @Aim => m_Wrapper.m_Extinguisher_Aim;
        public InputAction @Squeeze => m_Wrapper.m_Extinguisher_Squeeze;
        public InputAction @Sweep => m_Wrapper.m_Extinguisher_Sweep;
        public InputActionMap Get() { return m_Wrapper.m_Extinguisher; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ExtinguisherActions set) { return set.Get(); }
        public void AddCallbacks(IExtinguisherActions instance)
        {
            if (instance == null || m_Wrapper.m_ExtinguisherActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ExtinguisherActionsCallbackInterfaces.Add(instance);
            @Twist.started += instance.OnTwist;
            @Twist.performed += instance.OnTwist;
            @Twist.canceled += instance.OnTwist;
            @Pull.started += instance.OnPull;
            @Pull.performed += instance.OnPull;
            @Pull.canceled += instance.OnPull;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @Squeeze.started += instance.OnSqueeze;
            @Squeeze.performed += instance.OnSqueeze;
            @Squeeze.canceled += instance.OnSqueeze;
            @Sweep.started += instance.OnSweep;
            @Sweep.performed += instance.OnSweep;
            @Sweep.canceled += instance.OnSweep;
        }

        private void UnregisterCallbacks(IExtinguisherActions instance)
        {
            @Twist.started -= instance.OnTwist;
            @Twist.performed -= instance.OnTwist;
            @Twist.canceled -= instance.OnTwist;
            @Pull.started -= instance.OnPull;
            @Pull.performed -= instance.OnPull;
            @Pull.canceled -= instance.OnPull;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @Squeeze.started -= instance.OnSqueeze;
            @Squeeze.performed -= instance.OnSqueeze;
            @Squeeze.canceled -= instance.OnSqueeze;
            @Sweep.started -= instance.OnSweep;
            @Sweep.performed -= instance.OnSweep;
            @Sweep.canceled -= instance.OnSweep;
        }

        public void RemoveCallbacks(IExtinguisherActions instance)
        {
            if (m_Wrapper.m_ExtinguisherActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IExtinguisherActions instance)
        {
            foreach (var item in m_Wrapper.m_ExtinguisherActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ExtinguisherActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ExtinguisherActions @Extinguisher => new ExtinguisherActions(this);

    // TwistFE
    private readonly InputActionMap m_TwistFE;
    private List<ITwistFEActions> m_TwistFEActionsCallbackInterfaces = new List<ITwistFEActions>();
    private readonly InputAction m_TwistFE_Button1;
    private readonly InputAction m_TwistFE_Button2;
    private readonly InputAction m_TwistFE_Button3;
    private readonly InputAction m_TwistFE_Button4;
    public struct TwistFEActions
    {
        private @PlayerControls m_Wrapper;
        public TwistFEActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Button1 => m_Wrapper.m_TwistFE_Button1;
        public InputAction @Button2 => m_Wrapper.m_TwistFE_Button2;
        public InputAction @Button3 => m_Wrapper.m_TwistFE_Button3;
        public InputAction @Button4 => m_Wrapper.m_TwistFE_Button4;
        public InputActionMap Get() { return m_Wrapper.m_TwistFE; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TwistFEActions set) { return set.Get(); }
        public void AddCallbacks(ITwistFEActions instance)
        {
            if (instance == null || m_Wrapper.m_TwistFEActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TwistFEActionsCallbackInterfaces.Add(instance);
            @Button1.started += instance.OnButton1;
            @Button1.performed += instance.OnButton1;
            @Button1.canceled += instance.OnButton1;
            @Button2.started += instance.OnButton2;
            @Button2.performed += instance.OnButton2;
            @Button2.canceled += instance.OnButton2;
            @Button3.started += instance.OnButton3;
            @Button3.performed += instance.OnButton3;
            @Button3.canceled += instance.OnButton3;
            @Button4.started += instance.OnButton4;
            @Button4.performed += instance.OnButton4;
            @Button4.canceled += instance.OnButton4;
        }

        private void UnregisterCallbacks(ITwistFEActions instance)
        {
            @Button1.started -= instance.OnButton1;
            @Button1.performed -= instance.OnButton1;
            @Button1.canceled -= instance.OnButton1;
            @Button2.started -= instance.OnButton2;
            @Button2.performed -= instance.OnButton2;
            @Button2.canceled -= instance.OnButton2;
            @Button3.started -= instance.OnButton3;
            @Button3.performed -= instance.OnButton3;
            @Button3.canceled -= instance.OnButton3;
            @Button4.started -= instance.OnButton4;
            @Button4.performed -= instance.OnButton4;
            @Button4.canceled -= instance.OnButton4;
        }

        public void RemoveCallbacks(ITwistFEActions instance)
        {
            if (m_Wrapper.m_TwistFEActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITwistFEActions instance)
        {
            foreach (var item in m_Wrapper.m_TwistFEActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TwistFEActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TwistFEActions @TwistFE => new TwistFEActions(this);

    // PullFE
    private readonly InputActionMap m_PullFE;
    private List<IPullFEActions> m_PullFEActionsCallbackInterfaces = new List<IPullFEActions>();
    private readonly InputAction m_PullFE_Action;
    private readonly InputAction m_PullFE_ActionLock;
    public struct PullFEActions
    {
        private @PlayerControls m_Wrapper;
        public PullFEActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Action => m_Wrapper.m_PullFE_Action;
        public InputAction @ActionLock => m_Wrapper.m_PullFE_ActionLock;
        public InputActionMap Get() { return m_Wrapper.m_PullFE; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PullFEActions set) { return set.Get(); }
        public void AddCallbacks(IPullFEActions instance)
        {
            if (instance == null || m_Wrapper.m_PullFEActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PullFEActionsCallbackInterfaces.Add(instance);
            @Action.started += instance.OnAction;
            @Action.performed += instance.OnAction;
            @Action.canceled += instance.OnAction;
            @ActionLock.started += instance.OnActionLock;
            @ActionLock.performed += instance.OnActionLock;
            @ActionLock.canceled += instance.OnActionLock;
        }

        private void UnregisterCallbacks(IPullFEActions instance)
        {
            @Action.started -= instance.OnAction;
            @Action.performed -= instance.OnAction;
            @Action.canceled -= instance.OnAction;
            @ActionLock.started -= instance.OnActionLock;
            @ActionLock.performed -= instance.OnActionLock;
            @ActionLock.canceled -= instance.OnActionLock;
        }

        public void RemoveCallbacks(IPullFEActions instance)
        {
            if (m_Wrapper.m_PullFEActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPullFEActions instance)
        {
            foreach (var item in m_Wrapper.m_PullFEActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PullFEActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PullFEActions @PullFE => new PullFEActions(this);
    public interface ILoadingUIActions
    {
        void OnAction(InputAction.CallbackContext context);
    }
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnExamine(InputAction.CallbackContext context);
    }
    public interface IPlayerLayingDownActions
    {
        void OnLook(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
    }
    public interface IExamineActions
    {
        void OnLock(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnGamepadRotation(InputAction.CallbackContext context);
        void OnRead(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
    public interface ISpeechDialogueActions
    {
        void OnAction(InputAction.CallbackContext context);
        void OnOption1(InputAction.CallbackContext context);
        void OnOption2(InputAction.CallbackContext context);
        void OnOption3(InputAction.CallbackContext context);
    }
    public interface IContactActions
    {
        void OnContact1(InputAction.CallbackContext context);
        void OnContact2(InputAction.CallbackContext context);
        void OnContact3(InputAction.CallbackContext context);
    }
    public interface IExtinguisherActions
    {
        void OnTwist(InputAction.CallbackContext context);
        void OnPull(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnSqueeze(InputAction.CallbackContext context);
        void OnSweep(InputAction.CallbackContext context);
    }
    public interface ITwistFEActions
    {
        void OnButton1(InputAction.CallbackContext context);
        void OnButton2(InputAction.CallbackContext context);
        void OnButton3(InputAction.CallbackContext context);
        void OnButton4(InputAction.CallbackContext context);
    }
    public interface IPullFEActions
    {
        void OnAction(InputAction.CallbackContext context);
        void OnActionLock(InputAction.CallbackContext context);
    }
}
